# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x908sw1jUgcnyG5E0hCBbBoUtt7eIPVo
"""

import requests
from bs4 import BeautifulSoup

url= "https://www.exchangerates.org.uk/Dollars-to-Egyptian-Pounds-currency-conversion-page.html"
response = requests.get(url)
print(response.text)

soup= BeautifulSoup(response.text , 'html.parser')

soup.find('div')

rate = soup.find('tr')
print(rate.text)

print (f'This is the exchange value {rate.text}')

print("To exchange from Dollars to EGP , enter the amount of USD Dollars")
Dollars=float(input())

print(f'the amount of EGP is = {Dollars*15.6948 }')

