# -*- coding: utf-8 -*-
"""task 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KF_hMpM0EkKEfXB5k9ziT0QReLXjJ0OD
"""

import requests , json
from bs4 import BeautifulSoup

url='http://books.toscrape.com/catalogue/category/books/science_22/index.html'
response=requests.get(url)
print(response.text)

type(response.text)

soup = BeautifulSoup(response.text, 'html.parser')

categ=soup.find('div', attrs={'class': 'side_categories'})
print(categ.text)

rate=soup.find('p')
print(rate)

cost= soup.find('div' , attrs={'class' : 'product_price'} )
print(cost.text)



